In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation as R
from astropy import coordinates as ac
import copy
import torch

import os 
from os.path import join, split,exists, isdir,isfile

file_root =  join(os.getcwd(),'..')
os.chdir(file_root)

from utils.pc_utils import *
from utils import * 


from utils.utils import * 
import numpy as np 



In [9]:

class PredictionLoader:

    def __init__(self,root):
        self.root = root
        

        self.pc_pred_path = join(root,'point_predict')
        self.pc_pred_list = sorted(os.listdir(self.pc_pred_path))

        self.uncertainty_path = join(root,'uncertainty')
        self.uncertainty_list = sorted(os.listdir(self.uncertainty_path))

        self.name_list = [x.split('.')[0] for x in self.uncertainty_list]

        assert len(self.uncertainty_list) == len(self.pc_pred_list )

    def __len__(self):
        return len(self.uncertainty_list)
    
    
    def name2idx(self,name):
        return self.name_list.index(name)
    
    def idx2name(self,idx):
        return self.name_list[idx]

    def __getitem__(self,idx):

        return np.fromfile(join(self.pc_pred_path,self.pc_pred_list[idx]), dtype=np.uint32),\
             np.fromfile(join(self.uncertainty_path,self.uncertainty_list[idx]), dtype=np.uint32)
        
        
    def tmp(self):
        pc_pred ,uncertainty= self.__getitem__(0)
        
        print(np.unique(pc_pred),len(np.unique(pc_pred)))

    


prediction_root = '/data1/liyang/semantic_kitti_api-master/datasets/predictions/sequences/08/n19_four_losses_with_shapenet_anomaly'






epoch_names= sorted(os.listdir(prediction_root),key=lambda k: int(k.split('_')[-1]))

for epoch_name in epoch_names:
    loader = PredictionLoader(join(prediction_root,epoch_name))
    loader.tmp()






[10 11 30 31 32 40 44 48 49 50 51 70 71 72 80 81] 16
[10 18 30 40 44 48 49 50 51 70 71 72 80 81] 14
[10 15 18 30 31 32 40 44 48 49 50 51 70 71 72 80 81] 17
[10 15 18 30 40 44 48 49 50 51 70 71 72 80 81] 15
[10 15 18 30 31 40 44 48 50 51 70 71 72 80 81] 15
[10 18 30 31 32 40 44 48 49 50 51 70 71 72 80 81] 16
[10 11 18 30 31 40 44 48 49 50 51 70 71 72 80 81] 16
[10 18 30 31 40 44 48 49 50 51 70 71 72 80 81] 15
[10 18 30 31 40 44 48 50 51 70 71 72 80 81] 14
[10 18 30 31 40 44 48 50 51 70 71 72 80 81] 14
[10 11 18 30 31 40 44 48 50 51 70 71 72 80 81] 15
[10 18 30 40 44 48 50 51 70 71 72 80 81] 13
[10 18 30 31 40 44 48 49 50 51 70 71 72 80 81] 15
[10 15 18 30 40 44 48 50 51 70 71 72 80 81] 14
[10 18 30 31 40 44 48 50 51 70 71 72 80 81] 14
[10 18 30 31 40 44 48 50 51 70 71 72 80 81] 14
[10 18 30 31 40 44 48 49 50 51 70 71 72 80 81] 15
[10 18 30 31 40 44 48 49 50 51 70 71 72 80 81] 15
[10 11 18 30 31 40 44 48 49 50 51 70 71 72 80 81] 16
[10 11 15 18 30 31 40 44 48 49 50 51 70 71 72 80 81] 17


In [3]:
pc_pred, uncertainty=loader.__getitem__(0)

## check label 

In [15]:
from entity.semantic_kitti_gt_loader import SementicKittiGtLoader

gt_loader = SementicKittiGtLoader('datasets/dataset','08')



In [16]:
label = gt_loader.get_label(0)

000000.label


In [18]:
np.unique(label),len(label)

(array([       0,        1,       30,       40,       44,       48,
              50,       51,       52,       70,       71,       72,
              80,       81,       99,    65788,    65790,   131324,
          131326,   196860,   196862,   589854,   983070,  1572875,
         1638411, 12713994, 12779530, 12845066, 12976138], dtype=uint32),
 123389)