In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation as R
from astropy import coordinates as ac
import copy
import torch

import os 
from os.path import join, split,exists, isdir,isfile

file_root =  join(os.getcwd(),'..')
os.chdir(file_root)

from utils.pc_utils import *
from utils import * 


from utils.utils import * 
import numpy as np 


from entity.prediction_loader import PredictionLoader,MultiPredictionLoader

from entity.semantic_kitti_gt_loader import SementicKittiGtLoader,MultiSementicKittiGtLoader




In [10]:
# loader = MultiSementicKittiGtLoader('datasets/dataset',['08','09'])
loader = MultiSementicKittiGtLoader('datasets/dataset',['08','09','10'])


pred_loader = MultiPredictionLoader('datasets/predictions/Jan19_four_losses_with_shapenet_anomaly/model_epoch_39',['08'])


In [11]:
print(len(loader),loader[0])
print(len(pred_loader),pred_loader[0])


6863 datasets/dataset/sequences/08/labels/000000.label
4071 ('datasets/predictions/Jan19_four_losses_with_shapenet_anomaly/model_epoch_39/sequences/08/point_predict/000000.label', 'datasets/predictions/Jan19_four_losses_with_shapenet_anomaly/model_epoch_39/sequences/08/uncertainty/000000.label')


In [8]:
len(loader),loader[0]


(6863, 'datasets/dataset/sequences/08/labels/000000.label')

In [2]:
'''
Author: daniel
Date: 2023-03-21 16:15:50
LastEditTime: 2023-03-21 20:54:54
LastEditors: daniel
Description: 
FilePath: /semantic_kitti_api-master/jupyters/vis_remap.ipynb
have a nice day
'''



semantic_gt_loader = SementicKittiGtLoader('datasets/dataset')
prediction_root = 'datasets/predictions/Jan19_four_losses_with_shapenet_anomaly'
epoch_names= sorted(os.listdir(prediction_root),key=lambda k: int(k.split('_')[-1]))

for epoch_name in epoch_names:
    loader = PredictionLoader(join(prediction_root,epoch_name),'08')
    # loader.tmp()
    if loader.is_mapped() and loader.__len__() == semantic_gt_loader.__len__() :  
        print(epoch_name,'is mapped ')
    else :
        print(epoch_name,'is not  mapped ')
    


model_epoch_0 is mapped 
model_epoch_1 is mapped 
model_epoch_2 is mapped 
model_epoch_3 is mapped 
model_epoch_4 is mapped 
model_epoch_5 is mapped 
model_epoch_6 is mapped 
model_epoch_7 is mapped 
model_epoch_8 is mapped 
model_epoch_9 is mapped 
model_epoch_10 is mapped 
model_epoch_11 is mapped 
model_epoch_12 is mapped 
model_epoch_13 is mapped 
model_epoch_14 is mapped 
model_epoch_15 is mapped 
model_epoch_16 is mapped 
model_epoch_17 is mapped 
model_epoch_18 is mapped 
model_epoch_19 is mapped 
model_epoch_20 is mapped 
model_epoch_21 is mapped 
model_epoch_22 is mapped 
model_epoch_23 is mapped 
model_epoch_24 is mapped 
model_epoch_25 is mapped 
model_epoch_26 is mapped 
model_epoch_27 is mapped 
model_epoch_28 is mapped 
model_epoch_29 is mapped 
model_epoch_30 is mapped 
model_epoch_31 is mapped 
model_epoch_32 is mapped 
model_epoch_33 is mapped 
model_epoch_34 is mapped 
model_epoch_35 is mapped 
model_epoch_36 is mapped 
model_epoch_37 is mapped 
model_epoch_38 is mapp

In [3]:
pc_pred, uncertainty=loader.__getitem__(0)

In [7]:
loader.getitem(0), loader[0]

((array([70, 70, 70, ..., 48, 48, 48], dtype=uint32),
  array([0.43997207, 0.43997207, 0.6916288 , ..., 0.04604327, 0.04604327,
         0.04604327], dtype=float32)),
 ('datasets/predictions/Jan19_four_losses_with_shapenet_anomaly/model_epoch_49/sequences/08/point_predict/000000.label',
  'datasets/predictions/Jan19_four_losses_with_shapenet_anomaly/model_epoch_49/sequences/08/uncertainty/000000.label'))

## check label 

In [4]:
from entity.semantic_kitti_gt_loader import SementicKittiGtLoader

gt_loader = SementicKittiGtLoader('datasets/dataset','08')



In [6]:
sem,inst = gt_loader.get_label(0)

000000.label


In [8]:
np.unique(sem),len(sem),np.unique(inst),len(inst),

(array([  0,   1,  10,  11,  30,  40,  44,  48,  50,  51,  52,  70,  71,
         72,  80,  81,  99, 252, 254], dtype=uint32),
 123389,
 array([  0,   1,   2,   3,   9,  15,  24,  25, 194, 195, 196, 198],
       dtype=uint32),
 123389)